##Spring Configuration
server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  application:
    name: #TODO: Set email user
  node:
    name: #TODO: Set name.lastame
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
  rabbitmq: #TODO: Configure rabbit connection
    host:
    port:
    username:
    password: